### ISSUE TITLE
(node:19996) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'vendors' of null

### ISSUE THREAD

**Issue by Alien3389** [WongYuYe/jd_qianggou#4]
这是什么问题？[https://i.ibb.co/NxXyXHr/QQ-20210819100452.png](url)

**Comment by WongYuYe** [comment]
> 这是什么问题？
> `(node:19996) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'vendors' of null at D:\Github\jd_qianggou\jd_v3\index.js:152:39 at processTicksAndRejections (internal/process/task_queues.js:95:5) (Use `node --trace-warnings ...`to show where the warning was created) (node:19996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag`--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) (node:19996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

你应该是购物车内没商品，先随便加个商品进车，不勾选，再抢购要的商品。这个问题我修一下

**Comment by WongYuYe** [comment]
> > 这是什么问题？
> > `(node:19996) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'vendors' of null at D:\Github\jd_qianggou\jd_v3\index.js:152:39 at processTicksAndRejections (internal/process/task_queues.js:95:5) (Use `node --trace-warnings ...`to show where the warning was created) (node:19996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag`--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) (node:19996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
> 
> 你应该是购物车内没商品，先随便加个商品进车，不勾选，再抢购要的商品。这个问题我修一下

修好了，再拉一下

**Comment by Alien3389** [comment]
> > > 这是什么问题？
> > > `(node:19996) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'vendors' of null at D:\Github\jd_qianggou\jd_v3\index.js:152:39 at processTicksAndRejections (internal/process/task_queues.js:95:5) (Use `node --trace-warnings ...`to show where the warning was created) (node:19996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag`--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) (node:19996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
> > 
> > 
> > 你应该是购物车内没商品，先随便加个商品进车，不勾选，再抢购要的商品。这个问题我修一下
> 
> 修好了，再拉一下

OK，还有一个，我提交订单要输入支付密码，能不能加一个？

**Comment by WongYuYe** [comment]
> > > > 这是什么问题？
> > > > `(node:19996) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'vendors' of null at D:\Github\jd_qianggou\jd_v3\index.js:152:39 at processTicksAndRejections (internal/process/task_queues.js:95:5) (Use `node --trace-warnings ...`to show where the warning was created) (node:19996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag`--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) (node:19996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
> > > 
> > > 
> > > 你应该是购物车内没商品，先随便加个商品进车，不勾选，再抢购要的商品。这个问题我修一下
> > 
> > 
> > 修好了，再拉一下
> 
> OK，还有一个，我提交订单要输入支付密码，能不能加一个？
> 如果用红包或豆子就要支付密码，默认自动选了红包，所以要支付密码才能提交订单

嗯。支付密码的问题要等等
